# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciperating',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reciperating',
            name='recipe_r_name',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('dash', 'dash'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('fl oz', 'fl oz'), ('cup', 'cup'), ('pint', 'pint'), ('quart', 'quart'), ('ml', 'ml'), ('cc', 'cc'), ('liter', 'liter'), ('lb', 'lb'), ('oz', 'oz'), ('mg', 'mg'), ('g', 'g'), ('kg', 'kg'), ('pieces', 'pieces'), ('whole', 'whole'), ('slice', 'slice')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='RecipeRating',
        ),
    ]
