# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealtype',
            name='name',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Appetizer', 'Appetizer'), ('Side_Dish', 'Side Dish'), ('Dessert', 'Dessert')], max_length=100),
        ),
    ]
