# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 04:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe_app', '0002_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='fav_recipe',
        ),
        migrations.AddField(
            model_name='favorite',
            name='fav_recipe',
            field=models.ManyToManyField(default=False, to='recipe_app.Recipe'),
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='fav_user',
        ),
        migrations.AddField(
            model_name='favorite',
            name='fav_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
