# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_auto_20161013_0418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciperating',
            old_name='recipe_name',
            new_name='recipe',
        ),
    ]
