# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0003_auto_20161016_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('tsp', 'tsp'), ('tbsp', 'tbsp'), ('fl oz', 'fl oz'), ('cup', 'cup'), ('pint', 'pint'), ('quart', 'quart'), ('ml', 'ml'), ('cc', 'cc'), ('liter', 'liter'), ('lb', 'lb'), ('oz', 'oz'), ('mg', 'mg'), ('g', 'g'), ('kg', 'kg'), ('pieces', 'pieces'), ('whole', 'whole')], max_length=100, null=True),
        ),
    ]
