# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0003_auto_20161101_0454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='fav_recipe',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='fav_user',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
