# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0004_auto_20161008_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='measurement',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(default='fix_this', on_delete=django.db.models.deletion.CASCADE, to='recipe_app.Recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='ingredient',
            field=models.ForeignKey(default='fix_this', on_delete=django.db.models.deletion.CASCADE, to='recipe_app.Ingredient'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='title',
        ),
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='fix_this', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RecipeName',
        ),
    ]
